// Pre-build script: reads all adapter JS files and generates src/adapters-data.ts
// This allows Bun to bundle adapter code into the compiled binary

import { readdir, readFile } from "fs/promises";
import { join } from "path";

const ADAPTERS_DIR = join(import.meta.dir, "adapters", "doubao");
const OUT_FILE = join(import.meta.dir, "src", "adapters-data.ts");

async function main() {
  const files = await readdir(ADAPTERS_DIR);
  const jsFiles = files.filter((f) => f.endsWith(".js")).sort();

  const entries: string[] = [];
  for (const file of jsFiles) {
    const name = file.replace(/\.js$/, "");
    const code = await readFile(join(ADAPTERS_DIR, file), "utf-8");
    // Escape template literals and backslashes
    const escaped = code.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$/g, "\\$");
    entries.push(`  "${name}": \`${escaped}\``);
  }

  const content = `// Auto-generated by generate-adapters.ts — DO NOT EDIT
export const adapterSources: Record<string, string> = {
${entries.join(",\n")}
};
`;

  const { writeFile } = await import("fs/promises");
  await writeFile(OUT_FILE, content);
  console.log(`Generated ${OUT_FILE} with ${jsFiles.length} adapters`);
}

main();
